name: "PHP"
description: "Setup PHP"

inputs:
  php-version:
    required: false
    type: string
    default: "8.2"
    description: "PHP version to install"

  php-extensions:
    required: false
    type: string
    default: "json"
    description: "PHP extensions to install"

  php-tools:
    required: false
    type: string
    default: "composer:v2, cs2pr"
    description: "Composer tools"

  php-ini:
    required: false
    type: string
    default: "zend.assertions=1, assert.exception=1"
    description: "PHP additional extensions"

  php-coverage:
    required: false
    type: string
    default: "xdebug"
    description: "Code coverage settings"

runs:
  using: "composite"

  steps:
    - name: "Setup PHP cache environment"
      id: "extcache"
      uses: "shivammathur/cache-extensions@v1"
      with:
        php-version: "${{ inputs.php-version }}"
        extensions: "${{ inputs.php-extensions }}"
        key: "v1"

    - name: "Cache PHP extensions"
      uses: "actions/cache@v4"
      with:
        path: "${{ steps.extcache.outputs.dir }}"
        key: "${{ steps.extcache.outputs.key }}"
        restore-keys: "${{ steps.extcache.outputs.key }}"

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ inputs.php-version }}"
        extensions: "${{ inputs.php-extensions }}"
        tools: "${{ inputs.php-tools }}"
        ini-values: "${{ inputs.php-ini }}"
        coverage: "${{ inputs.php-coverage }}"

    - name: "Setup problem matchers for PHP"
      shell: "bash"
      run: 'echo "::add-matcher::${{ runner.tool_cache }}/php.json"'
