name: "Lerna Coding Linting"

on:
  workflow_call:
    inputs:
      node:
        required: false
        type: string
        default: "20"

      yarn:
        required: false
        type: string
        default: "yarn install"

jobs:
  qa:
    name: "Coding Linting (Node ${{ inputs.node }})"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup node"
        uses: "actions/setup-node@v4"
        with:
          node-version: "${{ inputs.node }}"

      - name: "Yarn"
        uses: "fastybird/.github/.github/actions/setup-yarn@main"
        with:
          command: "${{ inputs.yarn }}"

      - name: "Initialize lerna"
        run: "yarn bootstrap"

      - name: "Link dependencies"
        run: "yarn lerna link"

      - name: "Build dependencies"
        run: "yarn build"

      - name: "Check js linter"
        run: "yarn lint:js"

      - name: "Check styles linter"
        run: "yarn lint:styles"
